DROP TABLE IF EXISTS subscriber;

CREATE TABLE subscriber (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT NOT NULL UNIQUE,
    location TEXT,
    status TEXT
);
